# This is a basic workflow to help you get started with Actions

name: Test Intigrity Of Build
# Controls when the workflow will run
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Lint All Projects
        run: yarn nx run-many --target=lint --all=true

      - name: Test All Projects
        run: yarn nx run-many --target=test --all=true

      - name: Build All Projects
        run: yarn nx run-many --target=build --all=true

      - name: Pack All Server
        run: yarn nx run-many --target=pack --all=true
